// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package chuangyou_touyuan_example_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Example struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Example) Reset()         { *m = Example{} }
func (m *Example) String() string { return proto.CompactTextString(m) }
func (*Example) ProtoMessage()    {}
func (*Example) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

func (m *Example) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Example.Unmarshal(m, b)
}
func (m *Example) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Example.Marshal(b, m, deterministic)
}
func (m *Example) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Example.Merge(m, src)
}
func (m *Example) XXX_Size() int {
	return xxx_messageInfo_Example.Size(m)
}
func (m *Example) XXX_DiscardUnknown() {
	xxx_messageInfo_Example.DiscardUnknown(m)
}

var xxx_messageInfo_Example proto.InternalMessageInfo

func (m *Example) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetExampleRequest struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetExampleRequest) Reset()         { *m = GetExampleRequest{} }
func (m *GetExampleRequest) String() string { return proto.CompactTextString(m) }
func (*GetExampleRequest) ProtoMessage()    {}
func (*GetExampleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}

func (m *GetExampleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExampleRequest.Unmarshal(m, b)
}
func (m *GetExampleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExampleRequest.Marshal(b, m, deterministic)
}
func (m *GetExampleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExampleRequest.Merge(m, src)
}
func (m *GetExampleRequest) XXX_Size() int {
	return xxx_messageInfo_GetExampleRequest.Size(m)
}
func (m *GetExampleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExampleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetExampleRequest proto.InternalMessageInfo

func (m *GetExampleRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Example)(nil), "chuangyou.touyuan.example.v1.Example")
	proto.RegisterType((*GetExampleRequest)(nil), "chuangyou.touyuan.example.v1.GetExampleRequest")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6) }

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x49, 0xce, 0x28, 0x4d, 0xcc,
	0x4b, 0xaf, 0xcc, 0x2f, 0xd5, 0x2b, 0xc9, 0x2f, 0xad, 0x2c, 0x4d, 0xcc, 0xd3, 0x83, 0x29, 0x28,
	0x33, 0x94, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc,
	0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0xe8, 0x55, 0x92, 0xe7, 0x62, 0x77,
	0x85, 0xa8, 0x15, 0x12, 0xe1, 0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x82, 0x70, 0x94, 0x34, 0xb9, 0x04, 0xdd, 0x53, 0x4b, 0xa0, 0x6a, 0x82, 0x52, 0x0b,
	0x4b, 0x53, 0x8b, 0x4b, 0xb0, 0x2b, 0x35, 0xea, 0x61, 0xe4, 0xe2, 0x83, 0x2a, 0x0c, 0x4e, 0x2d,
	0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0xaa, 0xe2, 0xe2, 0x42, 0xe8, 0x16, 0xd2, 0xd7, 0xc3, 0xe7, 0x52,
	0x3d, 0x0c, 0x7b, 0xa4, 0x54, 0xf1, 0x6b, 0x80, 0xaa, 0x56, 0x12, 0x69, 0xba, 0xfc, 0x64, 0x32,
	0x13, 0x9f, 0x10, 0x8f, 0x7e, 0x99, 0xa1, 0x3e, 0x54, 0xbe, 0x38, 0x89, 0x0d, 0xec, 0x43, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x97, 0x69, 0x54, 0x2e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExampleServiceClient is the client API for ExampleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExampleServiceClient interface {
	GetExample(ctx context.Context, in *GetExampleRequest, opts ...grpc.CallOption) (*Example, error)
}

type exampleServiceClient struct {
	cc *grpc.ClientConn
}

func NewExampleServiceClient(cc *grpc.ClientConn) ExampleServiceClient {
	return &exampleServiceClient{cc}
}

func (c *exampleServiceClient) GetExample(ctx context.Context, in *GetExampleRequest, opts ...grpc.CallOption) (*Example, error) {
	out := new(Example)
	err := c.cc.Invoke(ctx, "/chuangyou.touyuan.example.v1.ExampleService/GetExample", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExampleServiceServer is the server API for ExampleService service.
type ExampleServiceServer interface {
	GetExample(context.Context, *GetExampleRequest) (*Example, error)
}

func RegisterExampleServiceServer(s *grpc.Server, srv ExampleServiceServer) {
	s.RegisterService(&_ExampleService_serviceDesc, srv)
}

func _ExampleService_GetExample_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExampleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServiceServer).GetExample(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chuangyou.touyuan.example.v1.ExampleService/GetExample",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServiceServer).GetExample(ctx, req.(*GetExampleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExampleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chuangyou.touyuan.example.v1.ExampleService",
	HandlerType: (*ExampleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExample",
			Handler:    _ExampleService_GetExample_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example.proto",
}
