// Code generated by protoc-gen-go.
// source: example.proto
// DO NOT EDIT!

/*
Package qsfiservice_example_v1 is a generated protocol buffer package.

It is generated from these files:
	example.proto

It has these top-level messages:
	Example
	GetExampleRequest
*/
package qsfservice_example_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Example struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *Example) Reset()                    { *m = Example{} }
func (m *Example) String() string            { return proto.CompactTextString(m) }
func (*Example) ProtoMessage()               {}
func (*Example) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Example) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetExampleRequest struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *GetExampleRequest) Reset()                    { *m = GetExampleRequest{} }
func (m *GetExampleRequest) String() string            { return proto.CompactTextString(m) }
func (*GetExampleRequest) ProtoMessage()               {}
func (*GetExampleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetExampleRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Example)(nil), "qsfservice.example.v1.Example")
	proto.RegisterType((*GetExampleRequest)(nil), "qsfservice.example.v1.GetExampleRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ExampleService service

type ExampleServiceClient interface {
	GetExample(ctx context.Context, in *GetExampleRequest, opts ...grpc.CallOption) (*Example, error)
}

type exampleServiceClient struct {
	cc *grpc.ClientConn
}

func NewExampleServiceClient(cc *grpc.ClientConn) ExampleServiceClient {
	return &exampleServiceClient{cc}
}

func (c *exampleServiceClient) GetExample(ctx context.Context, in *GetExampleRequest, opts ...grpc.CallOption) (*Example, error) {
	out := new(Example)
	err := grpc.Invoke(ctx, "/qsfservice.example.v1.ExampleService/GetExample", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ExampleService service

type ExampleServiceServer interface {
	GetExample(context.Context, *GetExampleRequest) (*Example, error)
}

func RegisterExampleServiceServer(s *grpc.Server, srv ExampleServiceServer) {
	s.RegisterService(&_ExampleService_serviceDesc, srv)
}

func _ExampleService_GetExample_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExampleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServiceServer).GetExample(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qsfservice.example.v1.ExampleService/GetExample",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServiceServer).GetExample(ctx, req.(*GetExampleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExampleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qsfservice.example.v1.ExampleService",
	HandlerType: (*ExampleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExample",
			Handler:    _ExampleService_GetExample_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example.proto",
}

func init() { proto.RegisterFile("example.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2b, 0x2c, 0xcd, 0xca, 0x2c,
	0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x83, 0x49, 0x95, 0x19, 0x4a, 0xc9, 0xa4, 0xe7, 0xe7,
	0xa7, 0xe7, 0xa4, 0xea, 0x27, 0x16, 0x64, 0xea, 0x27, 0xe6, 0xe5, 0xe5, 0x97, 0x24, 0x96, 0x64,
	0xe6, 0xe7, 0x15, 0x43, 0x74, 0x29, 0xc9, 0x73, 0xb1, 0xbb, 0x42, 0xd4, 0x0a, 0x89, 0x70, 0xb1,
	0x96, 0x25, 0xe6, 0x94, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38, 0x4a, 0x9a,
	0x5c, 0x82, 0xee, 0xa9, 0x25, 0x50, 0x35, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0xd8, 0x95,
	0x1a, 0x75, 0x30, 0x72, 0xf1, 0x41, 0x15, 0x06, 0x43, 0xdc, 0x21, 0x54, 0xc6, 0xc5, 0x85, 0xd0,
	0x2d, 0xa4, 0xa9, 0x87, 0xdd, 0x8d, 0x7a, 0x18, 0x36, 0x48, 0xc9, 0xe3, 0x52, 0x0a, 0x55, 0xa7,
	0x24, 0xd3, 0x74, 0xf9, 0xc9, 0x64, 0x26, 0x31, 0x21, 0x11, 0xfd, 0x32, 0x43, 0x7d, 0xa8, 0x7c,
	0xb1, 0x7e, 0x35, 0xd8, 0x25, 0xb5, 0x49, 0x6c, 0x60, 0xdf, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x00, 0x58, 0x29, 0x71, 0x24, 0x01, 0x00, 0x00,
}
